# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rohithmg/Projects/gcov_demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rohithmg/Projects/gcov_demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohithmg/Projects/gcov_demo/CMakeFiles /home/rohithmg/Projects/gcov_demo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rohithmg/Projects/gcov_demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named code_coverage

# Build rule for target.
code_coverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code_coverage
.PHONY : code_coverage

# fast build rule for target.
code_coverage/fast:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/build
.PHONY : code_coverage/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/main.cpp.s
.PHONY : main.cpp.s

src/Taxi.o: src/Taxi.cpp.o

.PHONY : src/Taxi.o

# target to build an object file
src/Taxi.cpp.o:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Taxi.cpp.o
.PHONY : src/Taxi.cpp.o

src/Taxi.i: src/Taxi.cpp.i

.PHONY : src/Taxi.i

# target to preprocess a source file
src/Taxi.cpp.i:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Taxi.cpp.i
.PHONY : src/Taxi.cpp.i

src/Taxi.s: src/Taxi.cpp.s

.PHONY : src/Taxi.s

# target to generate assembly for a file
src/Taxi.cpp.s:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Taxi.cpp.s
.PHONY : src/Taxi.cpp.s

src/Truck.o: src/Truck.cpp.o

.PHONY : src/Truck.o

# target to build an object file
src/Truck.cpp.o:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Truck.cpp.o
.PHONY : src/Truck.cpp.o

src/Truck.i: src/Truck.cpp.i

.PHONY : src/Truck.i

# target to preprocess a source file
src/Truck.cpp.i:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Truck.cpp.i
.PHONY : src/Truck.cpp.i

src/Truck.s: src/Truck.cpp.s

.PHONY : src/Truck.s

# target to generate assembly for a file
src/Truck.cpp.s:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Truck.cpp.s
.PHONY : src/Truck.cpp.s

src/Vehicle.o: src/Vehicle.cpp.o

.PHONY : src/Vehicle.o

# target to build an object file
src/Vehicle.cpp.o:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Vehicle.cpp.o
.PHONY : src/Vehicle.cpp.o

src/Vehicle.i: src/Vehicle.cpp.i

.PHONY : src/Vehicle.i

# target to preprocess a source file
src/Vehicle.cpp.i:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Vehicle.cpp.i
.PHONY : src/Vehicle.cpp.i

src/Vehicle.s: src/Vehicle.cpp.s

.PHONY : src/Vehicle.s

# target to generate assembly for a file
src/Vehicle.cpp.s:
	$(MAKE) -f CMakeFiles/code_coverage.dir/build.make CMakeFiles/code_coverage.dir/src/Vehicle.cpp.s
.PHONY : src/Vehicle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... code_coverage"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Taxi.o"
	@echo "... src/Taxi.i"
	@echo "... src/Taxi.s"
	@echo "... src/Truck.o"
	@echo "... src/Truck.i"
	@echo "... src/Truck.s"
	@echo "... src/Vehicle.o"
	@echo "... src/Vehicle.i"
	@echo "... src/Vehicle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

